# Useful Libraries

In [1]:
import numpy as np
import pandas as pd

from sklearn import datasets

from sklearn import model_selection
from sklearn.tree import DecisionTreeClassifier

from sklearn.ensemble import RandomForestClassifier

from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# Data loading and Analysis

In [2]:
digits_data = datasets.load_digits()
print(digits_data)

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]]), 'target': array([0, 1, 2, ..., 8, 9, 8]), 'frame': None, 'feature_names': ['pixel_0_0', 'pixel_0_1', 'pixel_0_2', 'pixel_0_3', 'pixel_0_4', 'pixel_0_5', 'pixel_0_6', 'pixel_0_7', 'pixel_1_0', 'pixel_1_1', 'pixel_1_2', 'pixel_1_3', 'pixel_1_4', 'pixel_1_5', 'pixel_1_6', 'pixel_1_7', 'pixel_2_0', 'pixel_2_1', 'pixel_2_2', 'pixel_2_3', 'pixel_2_4', 'pixel_2_5', 'pixel_2_6', 'pixel_2_7', 'pixel_3_0', 'pixel_3_1', 'pixel_3_2', 'pixel_3_3', 'pixel_3_4', 'pixel_3_5', 'pixel_3_6', 'pixel_3_7', 'pixel_4_0', 'pixel_4_1', 'pixel_4_2', 'pixel_4_3', 'pixel_4_4', 'pixel_4_5', 'pixel_4_6', 'pixel_4_7', 'pixel_5_0', 'pixel_5_1', 'pixel_5_2', 'pixel_5_3', 'pixel_5_4', 'pixel_5_5', 'pixel_5_6', 'pixel_5_7', 'pixel_6_0', '

In [6]:
X = digits_data.data
df1= pd.DataFrame(X)
print(df1.shape)
print(df1)

(1797, 64)
       0    1     2     3     4     5    6    7    8    9   ...   54   55  \
0     0.0  0.0   5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1     0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2     0.0  0.0   0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0   
3     0.0  0.0   7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0   
4     0.0  0.0   0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...   ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...   
1792  0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  4.0  0.0   
1793  0.0  0.0   6.0  16.0  13.0  11.0  1.0  0.0  0.0  0.0  ...  1.0  0.0   
1794  0.0  0.0   1.0  11.0  15.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1795  0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  2.0  0.0   
1796  0.0  0.0  10.0  14.0   8.0   1.0  0.0  0.0  0.0  2.0  ...  8.0  0.0   

       56   57   58    59    60    61   62   63  
0     0.0  0.0

In [7]:
Y = digits_data.target
df2 = pd.DataFrame(Y)
print(df2.shape)
print(df2)

(1797, 1)
      0
0     0
1     1
2     2
3     3
4     4
...  ..
1792  9
1793  0
1794  8
1795  9
1796  8

[1797 rows x 1 columns]


# Data Splitting

In [8]:
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X,Y)

print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(1347, 64)
(1347,)
(450, 64)
(450,)


# Classification using Decision Tree Classifier

In [9]:
clf1 = DecisionTreeClassifier()

clf1.fit(X_train, Y_train)

DecisionTreeClassifier()

In [11]:
# Predictions on training data

Y_train_pred = clf1.predict(X_train)
print(Y_train_pred.shape)

print(confusion_matrix(Y_train, Y_train_pred))
print(classification_report(Y_train, Y_train_pred))


(1347,)
[[132   0   0   0   0   0   0   0   0   0]
 [  0 126   0   0   0   0   0   0   0   0]
 [  0   0 135   0   0   0   0   0   0   0]
 [  0   0   0 135   0   0   0   0   0   0]
 [  0   0   0   0 134   0   0   0   0   0]
 [  0   0   0   0   0 140   0   0   0   0]
 [  0   0   0   0   0   0 138   0   0   0]
 [  0   0   0   0   0   0   0 139   0   0]
 [  0   0   0   0   0   0   0   0 132   0]
 [  0   0   0   0   0   0   0   0   0 136]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       132
           1       1.00      1.00      1.00       126
           2       1.00      1.00      1.00       135
           3       1.00      1.00      1.00       135
           4       1.00      1.00      1.00       134
           5       1.00      1.00      1.00       140
           6       1.00      1.00      1.00       138
           7       1.00      1.00      1.00       139
           8       1.00      1.00      1.00       132
           9       1

In [12]:
# Predictions on Testing data

Y_test_pred = clf1.predict(X_test)
print(Y_test_pred.shape)

print(confusion_matrix(Y_test, Y_test_pred))
print(classification_report(Y_test, Y_test_pred))

(450,)
[[44  0  1  0  1  0  0  0  0  0]
 [ 0 46  1  0  1  0  0  1  1  6]
 [ 0  2 33  3  0  1  0  0  3  0]
 [ 0  1  1 36  0  1  0  3  3  3]
 [ 1  1  0  1 41  0  3  0  0  0]
 [ 0  1  0  1  0 39  0  0  1  0]
 [ 0  0  0  0  3  2 38  0  0  0]
 [ 0  1  0  1  0  0  0 38  0  0]
 [ 2  3  1  1  0  1  0  1 28  5]
 [ 0  1  1  1  0  4  0  2  2 33]]
              precision    recall  f1-score   support

           0       0.94      0.96      0.95        46
           1       0.82      0.82      0.82        56
           2       0.87      0.79      0.82        42
           3       0.82      0.75      0.78        48
           4       0.89      0.87      0.88        47
           5       0.81      0.93      0.87        42
           6       0.93      0.88      0.90        43
           7       0.84      0.95      0.89        40
           8       0.74      0.67      0.70        42
           9       0.70      0.75      0.73        44

    accuracy                           0.84       450
   macro avg

# Classification using Random Forest Classifier

In [13]:
clf2 = RandomForestClassifier()

clf2.fit(X_train, Y_train)

RandomForestClassifier()

In [14]:
# Predictions on training data

Y_train_pred = clf2.predict(X_train)
print(Y_train_pred.shape)

print(confusion_matrix(Y_train, Y_train_pred))
print(classification_report(Y_train, Y_train_pred))

(1347,)
[[132   0   0   0   0   0   0   0   0   0]
 [  0 126   0   0   0   0   0   0   0   0]
 [  0   0 135   0   0   0   0   0   0   0]
 [  0   0   0 135   0   0   0   0   0   0]
 [  0   0   0   0 134   0   0   0   0   0]
 [  0   0   0   0   0 140   0   0   0   0]
 [  0   0   0   0   0   0 138   0   0   0]
 [  0   0   0   0   0   0   0 139   0   0]
 [  0   0   0   0   0   0   0   0 132   0]
 [  0   0   0   0   0   0   0   0   0 136]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       132
           1       1.00      1.00      1.00       126
           2       1.00      1.00      1.00       135
           3       1.00      1.00      1.00       135
           4       1.00      1.00      1.00       134
           5       1.00      1.00      1.00       140
           6       1.00      1.00      1.00       138
           7       1.00      1.00      1.00       139
           8       1.00      1.00      1.00       132
           9       1

In [15]:
# Predictions on Testing data

Y_test_pred = clf2.predict(X_test)
print(Y_test_pred.shape)

print(confusion_matrix(Y_test, Y_test_pred))
print(classification_report(Y_test, Y_test_pred))

(450,)
[[46  0  0  0  0  0  0  0  0  0]
 [ 0 55  0  1  0  0  0  0  0  0]
 [ 0  0 42  0  0  0  0  0  0  0]
 [ 0  0  1 43  0  1  0  2  0  1]
 [ 0  0  0  0 47  0  0  0  0  0]
 [ 0  0  0  0  0 41  0  0  1  0]
 [ 1  1  0  0  0  0 41  0  0  0]
 [ 0  0  0  0  0  0  0 40  0  0]
 [ 0  1  0  0  0  0  0  1 40  0]
 [ 0  0  0  1  0  2  0  0  0 41]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99        46
           1       0.96      0.98      0.97        56
           2       0.98      1.00      0.99        42
           3       0.96      0.90      0.92        48
           4       1.00      1.00      1.00        47
           5       0.93      0.98      0.95        42
           6       1.00      0.95      0.98        43
           7       0.93      1.00      0.96        40
           8       0.98      0.95      0.96        42
           9       0.98      0.93      0.95        44

    accuracy                           0.97       450
   macro avg