# Useful Libraries

In [15]:
import numpy as np
import pandas as pd

from sklearn import datasets

from sklearn import model_selection
from sklearn.tree import DecisionTreeClassifier

from sklearn.ensemble import RandomForestClassifier

from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# Data Loading and Analysis

In [6]:
iris_data = datasets.load_iris()


In [7]:
X = iris_data.data
df1= pd.DataFrame(X)
print(df1.shape)
df1.describe()

(150, 4)


0           1           2           3
count  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.057333    3.758000    1.199333
std      0.828066    0.435866    1.765298    0.762238
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.350000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [8]:
Y = iris_data.target
df2= pd.DataFrame(Y)
print(df2.shape)
df2.describe()

(150, 1)


0
count  150.000000
mean     1.000000
std      0.819232
min      0.000000
25%      0.000000
50%      1.000000
75%      2.000000
max      2.000000

# Data Splitting

In [10]:
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X,Y)

print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(112, 4)
(38, 4)
(112,)
(38,)


# Classification using Decision Tree Classifier

In [13]:
# Training  for Decision Tree classifier
clf1 = DecisionTreeClassifier()

clf1.fit(X_train, Y_train)


DecisionTreeClassifier()

In [16]:
#Predictions on Training Data
Y_train_pred = clf1.predict(X_train)

print(confusion_matrix(Y_train, Y_train_pred))
print(classification_report(Y_train, Y_train_pred))

[[36  0  0]
 [ 0 39  0]
 [ 0  0 37]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        36
           1       1.00      1.00      1.00        39
           2       1.00      1.00      1.00        37

    accuracy                           1.00       112
   macro avg       1.00      1.00      1.00       112
weighted avg       1.00      1.00      1.00       112



In [17]:
#Predictions on testing data
Y_test_pred = clf1.predict(X_test)

print(confusion_matrix(Y_test, Y_test_pred))
print(classification_report(Y_test, Y_test_pred))

[[14  0  0]
 [ 0 10  1]
 [ 0  1 12]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.91      0.91      0.91        11
           2       0.92      0.92      0.92        13

    accuracy                           0.95        38
   macro avg       0.94      0.94      0.94        38
weighted avg       0.95      0.95      0.95        38



# Classification using Random Forest

In [18]:
clf2 = RandomForestClassifier()

clf2.fit(X_train, Y_train)

RandomForestClassifier()

In [19]:
#Predictions on Training Data
Y_train_pred = clf2.predict(X_train)

print(confusion_matrix(Y_train, Y_train_pred))
print(classification_report(Y_train, Y_train_pred))

[[36  0  0]
 [ 0 39  0]
 [ 0  0 37]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        36
           1       1.00      1.00      1.00        39
           2       1.00      1.00      1.00        37

    accuracy                           1.00       112
   macro avg       1.00      1.00      1.00       112
weighted avg       1.00      1.00      1.00       112



In [20]:
#Predictions on testing data
Y_test_pred = clf2.predict(X_test)

print(confusion_matrix(Y_test, Y_test_pred))
print(classification_report(Y_test, Y_test_pred))

[[14  0  0]
 [ 0 10  1]
 [ 0  0 13]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      0.91      0.95        11
           2       0.93      1.00      0.96        13

    accuracy                           0.97        38
   macro avg       0.98      0.97      0.97        38
weighted avg       0.98      0.97      0.97        38

