In [26]:
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.tree import export_graphviz

import numpy as np 
import pandas as pd
import pydotplus

In [27]:
pip install pydotplus

Note: you may need to restart the kernel to use updated packages.


In [28]:
mydata = datasets.load_iris()
print(mydata)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [29]:
X = mydata.data
df_X = pd.DataFrame(X)
df_X.columns = ['sepal_length','sepal_width','petal_length','petal_width']
print(df_X.shape)
df_X.describe()


(150, 4)


sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [30]:
Y = mydata.target
df_Y = pd.DataFrame(Y)
df_Y.columns = ['class_type']
print(df_Y.shape)
df_Y.describe()

(150, 1)


class_type
count  150.000000
mean     1.000000
std      0.819232
min      0.000000
25%      0.000000
50%      1.000000
75%      2.000000
max      2.000000

In [31]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y)


print("Training Data:")
print(X_train.shape)
print(Y_train.shape)

print("Testing Data:")
print(X_test.shape)
print(Y_test.shape)

Training Data:
(112, 4)
(112,)
Testing Data:
(38, 4)
(38,)


In [32]:
dt1 = DecisionTreeClassifier()

dt1.fit(X_train,Y_train)

DecisionTreeClassifier()

In [33]:
# to export realtime tree in pdf format built by the model

dot_data = export_graphviz(dt1, out_file=None,
                           feature_names = mydata.feature_names,
                           class_names = mydata.target_names)

graph = pydotplus.graph_from_dot_data(dot_data)

graph.write_pdf("iris.pdf")


InvocationException: GraphViz's executables not found

In [14]:
print("Predictions on training data: ")
Y_train_predict = dt1.predict(X_train)
print(Y_train_predict.shape)

Predictions on training data: 
(112,)


In [15]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [16]:
print(confusion_matrix(Y_train, Y_train_predict))
print(classification_report(Y_train, Y_train_predict))

[[34  0  0]
 [ 0 40  0]
 [ 0  0 38]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        34
           1       1.00      1.00      1.00        40
           2       1.00      1.00      1.00        38

    accuracy                           1.00       112
   macro avg       1.00      1.00      1.00       112
weighted avg       1.00      1.00      1.00       112



In [17]:
print("Predictions on testing data: ")
Y_test_predict = dt1.predict(X_test)
print(Y_test_predict.shape)

Predictions on testing data: 
(38,)


In [18]:
print(confusion_matrix(Y_test, Y_test_predict))
print(classification_report(Y_test, Y_test_predict))

[[16  0  0]
 [ 0 10  0]
 [ 0  2 10]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.83      1.00      0.91        10
           2       1.00      0.83      0.91        12

    accuracy                           0.95        38
   macro avg       0.94      0.94      0.94        38
weighted avg       0.96      0.95      0.95        38

