In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn import model_selection
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [3]:
digit_data = datasets.load_digits()
print(digit_data)

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]]), 'target': array([0, 1, 2, ..., 8, 9, 8]), 'frame': None, 'feature_names': ['pixel_0_0', 'pixel_0_1', 'pixel_0_2', 'pixel_0_3', 'pixel_0_4', 'pixel_0_5', 'pixel_0_6', 'pixel_0_7', 'pixel_1_0', 'pixel_1_1', 'pixel_1_2', 'pixel_1_3', 'pixel_1_4', 'pixel_1_5', 'pixel_1_6', 'pixel_1_7', 'pixel_2_0', 'pixel_2_1', 'pixel_2_2', 'pixel_2_3', 'pixel_2_4', 'pixel_2_5', 'pixel_2_6', 'pixel_2_7', 'pixel_3_0', 'pixel_3_1', 'pixel_3_2', 'pixel_3_3', 'pixel_3_4', 'pixel_3_5', 'pixel_3_6', 'pixel_3_7', 'pixel_4_0', 'pixel_4_1', 'pixel_4_2', 'pixel_4_3', 'pixel_4_4', 'pixel_4_5', 'pixel_4_6', 'pixel_4_7', 'pixel_5_0', 'pixel_5_1', 'pixel_5_2', 'pixel_5_3', 'pixel_5_4', 'pixel_5_5', 'pixel_5_6', 'pixel_5_7', 'pixel_6_0', '

In [7]:
X = digit_data.data
df_X = pd.DataFrame(X)
df_X.columns = digit_data.feature_names
print(df_X.shape)


(1797, 64)


In [13]:
Y = digit_data.target
df_Y = pd.DataFrame(Y)

print(df_Y.shape)


(1797, 1)


In [15]:
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X,Y)

print("Training Data:")
print(X_train.shape)
print(Y_train.shape)

print("Testing Data:")
print(X_test.shape)
print(Y_test.shape)

Training Data:
(1347, 64)
(1347,)
Testing Data:
(450, 64)
(450,)


In [27]:
clf1 = LogisticRegression(max_iter = 1000, solver = 'saga')

clf1.fit(X_train, Y_train)

LogisticRegression(max_iter=1000, solver='saga')

In [29]:
Y_train_predict = clf1.predict(X_train)

print(Y_train_predict.shape)

(1347,)


In [31]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

print(confusion_matrix(Y_train, Y_train_predict))

print(classification_report(Y_train, Y_train_predict))

[[148   0   0   0   0   0   0   0   0   0]
 [  0 130   0   0   0   0   0   0   0   0]
 [  0   0 130   0   0   0   0   0   0   0]
 [  0   0   0 140   0   0   0   0   0   0]
 [  0   0   0   0 136   0   0   0   0   0]
 [  0   0   0   0   0 134   0   0   0   0]
 [  0   0   0   0   0   0 143   0   0   0]
 [  0   0   0   0   0   0   0 128   0   0]
 [  0   0   0   0   0   0   0   0 133   0]
 [  0   0   0   0   0   0   0   0   0 125]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       148
           1       1.00      1.00      1.00       130
           2       1.00      1.00      1.00       130
           3       1.00      1.00      1.00       140
           4       1.00      1.00      1.00       136
           5       1.00      1.00      1.00       134
           6       1.00      1.00      1.00       143
           7       1.00      1.00      1.00       128
           8       1.00      1.00      1.00       133
           9       1.00     

In [32]:
Y_test_predict = clf1.predict(X_test)

print(Y_test_predict.shape)

(450,)


In [33]:
print(confusion_matrix(Y_test, Y_test_predict))

print(classification_report(Y_test, Y_test_predict))

[[30  0  0  0  0  0  0  0  0  0]
 [ 0 51  0  0  0  0  0  0  1  0]
 [ 0  1 46  0  0  0  0  0  0  0]
 [ 0  0  0 41  0  0  0  0  1  1]
 [ 0  1  0  0 44  0  0  0  0  0]
 [ 0  0  0  0  0 45  0  1  0  2]
 [ 0  1  0  0  0  0 37  0  0  0]
 [ 0  0  0  0  0  1  0 48  0  2]
 [ 0  0  0  0  1  0  0  0 40  0]
 [ 0  0  0  0  0  1  0  0  2 52]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        30
           1       0.94      0.98      0.96        52
           2       1.00      0.98      0.99        47
           3       1.00      0.95      0.98        43
           4       0.98      0.98      0.98        45
           5       0.96      0.94      0.95        48
           6       1.00      0.97      0.99        38
           7       0.98      0.94      0.96        51
           8       0.91      0.98      0.94        41
           9       0.91      0.95      0.93        55

    accuracy                           0.96       450
   macro avg       