___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [2]:
import numpy as np


#### Create an array of 10 zeros 

In [4]:
np.zeros(11)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [5]:
np.ones(11)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [8]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [10]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [12]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [21]:
np.random.rand(2)

array([0.11136207, 0.99387851])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [23]:
np.random.randn(25)

array([ 0.26045603,  0.20338907,  0.96400842, -0.45951462,  0.52086886,
        0.15585319, -1.65247013,  0.5604313 , -0.78875462, -0.37477862,
       -0.64431487, -0.30341405, -1.27121649, -0.76459667, -0.15418997,
       -0.17937775, -0.49937165,  1.17302901, -0.60922788,  0.66508624,
        0.98138749,  2.05727675,  0.00764906, -0.61705709, -0.01123275])

#### Create the following matrix:

In [27]:
np.random.randn(10,10)

array([[ 0.88265632,  0.7753071 , -0.27373556, -0.71069596, -0.25493275,
        -0.28156857,  1.16092811,  0.12149626,  1.25416929, -1.76201487],
       [ 2.6246805 ,  0.05540153, -0.5151027 ,  0.36506996, -0.30679407,
        -0.1884232 ,  0.38679953, -1.52587113,  0.38796205,  0.48430091],
       [-0.65628073,  0.05635715,  0.94219001,  0.12274945,  1.78887562,
        -0.64193744, -0.47327304, -0.66654193, -0.56736232,  0.96644405],
       [ 0.82596026, -0.36589938,  1.90651479,  0.46851653, -0.18947502,
         0.93727376, -0.2374342 ,  0.39696842, -0.38211008, -1.0666004 ],
       [-0.10653279, -0.54025653, -0.80066771,  0.73192562, -0.58970085,
         1.07389287, -0.49232503,  0.70190017,  0.96234426,  0.52378165],
       [ 0.23353242,  0.26358479, -0.54113741, -0.56152281, -0.17359791,
        -0.57770709, -0.73684093, -1.73956421,  0.0321661 , -0.87585593],
       [ 0.61864961, -0.38757297,  0.05122305, -0.25429312,  1.8498224 ,
         0.07120301,  1.00878747,  0.55929671

#### Create an array of 20 linearly spaced points between 0 and 1:

In [28]:
np.random.rand(20)


array([0.07177351, 0.54431902, 0.61157703, 0.21945838, 0.60423313,
       0.73861617, 0.07498369, 0.85747697, 0.12122922, 0.40253573,
       0.74128155, 0.01574487, 0.40521369, 0.48917802, 0.35817163,
       0.75352695, 0.41225895, 0.94188004, 0.27884542, 0.29707673])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [38]:
mat = np.arange(1,26).reshape(5,5)
mat


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat = np.arange(1,26).reshape(5,5)
mat
mat[2: , 1: ]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [38]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat = np.arange(1,26).reshape(5,5)
mat
mat[3:4, 4: ]

array([[20]])

20

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat = np.arange(1,26).reshape(5,5)
mat
mat[ 0:3, 1:2 ]

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [40]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat = np.arange(1,26).reshape(5,5)
mat
mat[ 4: ] 

array([[21, 22, 23, 24, 25]])

array([21, 22, 23, 24, 25])

In [41]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat = np.arange(1,26).reshape(5,5)
mat
mat[ 3: ] 

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [43]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [44]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

array([55, 60, 65, 70, 75])

# Great Job!